### PR TITLE
feat(metric): add the metric label `caicloud_app_key` to the `kube_pod_info` metric

### PR DESCRIPTION
**Pull request by lichuan0620**
**What this PR does / why we need it**:

* Added a configurable metric label to the `kube_pod_info` metric.
* The metric label name default to `caicloud_app_key`
* Its value is taken from a configurable Pod annotation default to `helm.sh/release`

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @jianglinjian @supereagle 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by supereagle — COMMENTED** [review]
LGTM

**Comment by supereagle** [comment]
Why the target branch is `cps-1.9`? Which version of CPS is this branch for?

**Comment by lichuan0620** [comment]
`cps-1.9` is based on the original `release-1.9`.

Since we intend to modify the source code, and potentially on multiple branches, we need our own branches that are based on the original ones; hence the `cps-x.x` name. 

It doesn't make sense to map the branches to CPS versions, as we are not planning on releasing a new release on every CPS release.

**Pull request merged**
